r"""
danmaku2ass 离线回归测试（不触网、无需凭据）。

背景：danmaku2ass.py 为上游移植的第三方代码（StarBrilliant/danmaku2ass），
2026-08-29 豁免清零（F821/UP031/E722/PYI056/B008/B904）时，为保证行为不变，
以修复前的真实输出为基线做前后 diff 对比，并将该基线固化为本快照测试。

样例弹幕覆盖：滚动/底部/顶部/反向弹幕、非默认字号、多种颜色（含黑色与
BT.709 转换路径）、多行弹幕、定位（高级）弹幕（\move/\t/\fade/\fn/\bord0）、
以及触发异常分支的坏弹幕。
"""

import io
import random

import pytest

from bilibili_api.utils import danmaku2ass

SAMPLE_XML = """<?xml version="1.0" encoding="UTF-8"?><i>\
<chatserver>chat.bilibili.com</chatserver>\
<d p="1.000,1,25,16777215,1700000000,0,aabbcc,10000001">普通滚动弹幕</d>\
<d p="2.500,1,18,65280,1700000001,0,aabbcd,10000002">小字号绿色滚动</d>\
<d p="3.000,5,25,255,1700000002,0,aabbce,10000003">底部居中红色</d>\
<d p="4.000,4,25,0,1700000003,0,aabbcf,10000004">顶部居中黑色</d>\
<d p="5.000,6,25,16711935,1700000004,0,aabbd0,10000005">反向滚动洋红</d>\
<d p="61.500,1,25,16777215,1700000005,0,aabbd1,10000006">多行弹幕第一行/n第二行</d>\
<d p="7.000,7,25,65280,1700000006,0,aabbd2,10000007">[0.1,0.1,"0.5-1",4500,"定位弹幕测试",0,0,0.9,0.9,4500000,100,"false","FZHei"]</d>\
<d p="bad">坏弹幕（触发异常分支）</d>\
</i>"""

# 修复前基线（random.seed(0) 固定 styleid），修复后输出与其逐字节一致
EXPECTED_ASS = """[Script Info]
; Script generated by Danmaku2ASS
; https://github.com/m13253/danmaku2ass
Script Updated By: Danmaku2ASS (https://github.com/m13253/danmaku2ass)
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
Aspect Ratio: 1920:1080
Collisions: Normal
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Danmaku2ASS_c53e, sans-serif, 25, &H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 7, 0, 0, 0, 0
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 2,0:00:01.00,0:00:06.00,Danmaku2ASS_c53e,,0000,0000,0000,,{\\move(1920, 0, -150, 0)}普通滚动弹幕
Dialogue: 2,0:00:02.50,0:00:07.50,Danmaku2ASS_c53e,,0000,0000,0000,,{\\move(1920, 0, -126, 0)\\fs18\\c&H08FF14&}小字号绿色滚动
Dialogue: 2,0:00:03.00,0:00:08.00,Danmaku2ASS_c53e,,0000,0000,0000,,{\\an8\\pos(960, 0)\\c&HF40002&}底部居中红色
Dialogue: 2,0:00:04.00,0:00:09.00,Danmaku2ASS_c53e,,0000,0000,0000,,{\\an2\\pos(960, 1080)\\c&H000000&\\3c&HFFFFFF&}顶部居中黑色
Dialogue: 2,0:00:05.00,0:00:10.00,Danmaku2ASS_c53e,,0000,0000,0000,,{\\move(-150, 0, 1920, 0)\\c&HF700EB&}反向滚动洋红
Dialogue: -1,0:00:07.00,1:15:07.00,Danmaku2ASS_c53e,,0,0,0,,{\\org(960, 540)\\move(297, 108, 1623, 972, 100, 4500100)\\frx0\\fry0\\frz0\\fscx100\\fscy100\\t(100, 4500100, \\frx0\\fry0\\frz0\\fscx100\\fscy100)\\fnFZHei\\fs62\\c&H08FF14&\\fade(127, 0, 0, 0, 4500000, 4500000, 4500000)\\bord0}定位弹幕测试
Dialogue: 2,0:01:01.50,0:01:06.50,Danmaku2ASS_c53e,,0000,0000,0000,,{\\move(1920, 0, -175, 0)}多行弹幕第一行\\N第二行
"""


def convert_sample(width: int = 1920, height: int = 1080, **kwargs) -> str:
    """将样例 Bilibili 弹幕 XML 转换为 ASS 文本（固定随机种子保证确定性）。"""
    random.seed(0)
    out = io.StringIO()
    danmaku2ass.Danmaku2ASS(
        input_files=[io.StringIO(SAMPLE_XML)],
        input_format="autodetect",
        output_file=out,
        stage_width=width,
        stage_height=height,
        **kwargs,
    )
    return out.getvalue()


def test_danmaku2ass_output_matches_pre_refactor_baseline():
    """豁免清零重构（2026-08-29）前后 ASS 输出必须逐字节一致。"""
    assert convert_sample() == EXPECTED_ASS


def test_danmaku2ass_output_is_deterministic_with_seed():
    assert convert_sample() == convert_sample()


def test_danmaku2ass_filters_invalid_regex():
    """非法过滤正则应抛 ValueError（E722/B904 修复后的异常链路径）。"""
    with pytest.raises(ValueError, match="Invalid regular expression"):
        convert_sample(comment_filter="[")


def test_readcomments_rejects_unknown_format():
    with pytest.raises(ValueError, match="Unknown comment file format"):
        danmaku2ass.ReadComments(
            input_files=[io.StringIO(SAMPLE_XML)],
            input_format="NoSuchFormat",
        )
